### ISSUE TITLE
neo feed crash

### ISSUE THREAD

**Issue by francoisrob** [NeoApplications/Neo-Feed#10]
a few mins after install and after adding some feeds.

11-05 14:42:20.692  7480  7480 E AndroidRuntime: FATAL EXCEPTION: main
11-05 14:42:20.692  7480  7480 E AndroidRuntime: Process: com.saulhdev.neofeed, PID: 7480
11-05 14:42:20.692  7480  7480 E AndroidRuntime: java.lang.NullPointerException
11-05 14:42:20.692  7480  7480 E AndroidRuntime:        at com.saulhdev.feeder.utils.HFPluginService$a$a$a.k(SourceFile:23)
11-05 14:42:20.692  7480  7480 E AndroidRuntime:        at hfcore.of.A(Unknown Source:8)
11-05 14:42:20.692  7480  7480 E AndroidRuntime:        at hfcore.e80.run(Unknown Source:86)
11-05 14:42:20.692  7480  7480 E AndroidRuntime:        at hfcore.zg1.run(Unknown Source:11)
11-05 14:42:20.692  7480  7480 E AndroidRuntime:        at hfcore.l03.run(Unknown Source:2)
11-05 14:42:20.692  7480  7480 E AndroidRuntime:        at hfcore.r00$a.run(SourceFile:9)
11-05 14:42:20.692  7480  7480 E AndroidRuntime:        Suppressed: hfcore.sv0: [eu2{Cancelling}@e29b634, Dispatchers.Main]
11-05 14:42:20.696  1362  7541 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
11-05 14:42:20.696  1362  4956 D Debug   : low && ship && 3rdparty app crash, do not dump
11-05 14:42:20.696  1362  4956 W ActivityManager: crash : com.saulhdev.neofeed,10419
11-05 14:42:20.696  1362  4956 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1242 com.android.server.am.AppErrors.crashApplicationInner:723 com.android.server.am.AppErrors.crashApplication:584 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:9745 com.android.server.am.ActivityManagerService.handleApplicationCrash:9624 
11-05 14:42:20.697  7480  7480 I Process : Sending signal. PID: 7480 SIG: 9
11-05 14:42:20.699  1362  1437 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
11-05 14:42:20.699  1362  1437 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
11-05 14:42:20.707  4207  4207 I SDHMS:BarTender:Gatherer:AppError: update AppError : uid=10419, pkg=com.saulhdev.neofeed, errorType=crash
11-05 14:42:20.716  4207  4207 I SDHMS:BarTender:Analyzer:AppError: analyze app error : uid=10419, pkg=com.saulhdev.neofeed, appErrorCount=2
11-05 14:42:20.724  1362  6485 D InputMethodManagerService: removeClient
11-05 14:42:20.724   867   867 I Zygote  : Process 7480 exited due to signal 9 (Killed)
11-05 14:42:20.725  1362  1401 I ActivityManager: Process com.saulhdev.neofeed (pid 7480) has died: fg  BTOP(366,4255)

**Comment by saulhdev** [comment]
I need more info: What version are you using?

**Comment by francoisrob** [comment]
> I need more info: What version are you using?

I'm using the latest version. 
v1.4.3 Build 40

**Comment by francoisrob** [comment]
> I need more info: What version are you using?

I tried to replicate it and after adding my third source and refreshing it crashes. Sometimes it adds the same source twice as well

**Comment by saulhdev** [comment]
This issue was fixed on v1.4.4. Note that the feed are migrated to room database instead of shared preferences, so you will have to add the feeds again.
