### ISSUE TITLE
FR: Smaler Entrys without Thumbnail

### ISSUE THREAD

**Issue by snoweuph** [NeoApplications/Neo-Feed#12]
There are some Feeds that dont Provide a Thumbnail like: https://itsfoss.com/feed/

currently these look like this ![Screenshot_20221111-112845_Neo Launcher.png](https://user-images.githubusercontent.com/76737863/201321835-bb247b33-54e7-4107-99fc-d8955e4f3069.png)

It would be cool if Entries without a Thumbnail would have less height.

**Comment by snoweuph** [comment]
Thx for the fast Implementation, but this doesnt seem to work for everything yet ![Screenshot_20221112-162706_Neo Launcher.png](https://user-images.githubusercontent.com/76737863/201481355-07cc8425-4d3b-495c-849f-5765cedd1e9c.png)

**Comment by saulhdev** [comment]
Fixed on v1.6.3
