### ISSUE TITLE
Add Neo Feed to Izzysoft repo

### ISSUE THREAD

**Issue by cellfdroid** [NeoApplications/Neo-Feed#15]
I see some Neo apps through Izzysoft repo - store, launcher, backup.

It would be great if Feed is made available through this repo as well as then it can be updated similar to all apps.

**Comment by ShareASmile** [comment]
Yes, that would be great,  cc IzzyOnDroid

**Comment by ShareASmile** [comment]
Yes, that would be great cc @IzzySoft

**Comment by machiav3lli** [comment]
Hey @IzzySoft , it's actually a normal rss-reader that can be embedded in place of google's discover thingy. It's mainly made for Neo-Launcher for now. We're still not ready for a "public release" or more precisly F-Droid release, @saulhdev would like to fix couple of small bugs and he or I will write here as soon as we're ready. Is it ok like this or should we move the discussion to your repo's repo?

**Comment by IzzySoft** [comment]
Thanks for the details, @machiav3lli & @cellfdroid! I had it already added and just updated the description now (plus the first 2 screenshots), clearly marking it a "pre-release". Should I disable it again for now – or are you OK with this making "App number 999" in my repo? And I of course can send you the metadata I've prepared as the usual "fastlane starter package" via PR if you wish – so you can remove the "early bird" marker whenever you feel it ready.

**Comment by machiav3lli** [comment]
@IzzySoft I've wrote Saul and it's ok to keep it up with pre-release tag.
How can we take number 1000 😆? You see, we also have [Neo Wellbeing](https://github.com/NeoApplications/Neo-Wellbeing) which is still in pretty early alpha and is meant to be a Magisk Module, but maybe, maybe the honorary number 1000 is seducing enough, @nift4 ?

Before drifting too much further, you can gladly PR the "starter package".

**Comment by nift4** [comment]
People seeing an app, installing it, just to notice the repo entry is only good for updating the app, i'm sure that will frustrate too many users

**Comment by machiav3lli** [comment]
@nift4 hehe, I didn't mean it seriously. But, now talking about it, maybe it can include an internal installer like Iconify (the app seems to be taken down with a dmca)

**Comment by IzzySoft** [comment]
No worries @nift4 – no APK there so I have nothing to pick anyway. But you're always welcome!

@machiav3lli I'll prepare the PR then. While I can certainly skip the usual notes with it, you will look a bit puzzled at the `full_description.pl` I guess. That's not the Polish description, but a Perl script: we recently figured several F-Droid clients (unfortunately including NeoStore) add a bunch of extra line breaks, seemingly converting all newlines to `<br>` (if I got that right it was the htmlviewer library used causing that). A work around is having full HTML wrapped in a Perl script (for easier editing) which then on being run "condenses" the HTML to a single line (which would break any `<pre>`, but that's rarely used).

So you want that variant – or the usual "Markdown Lite"?

**Comment by machiav3lli** [comment]
Yeah, we'll possibly merge as it is and see from there, what to do, when we have a stable release. I'll also see what I can do on NS's side, as soon as am over with these health issues and the BA-thesis.

And, ping me again when there's again a unique number to get.

**Comment by citizenserious** [comment]
![Screenshot_20221212-231950_Neo_Launcher](https://user-images.githubusercontent.com/62773866/207171146-98266ee7-465f-4c77-91a4-ac80f9c07e9a.png)
![Screenshot_20221212-231733_Neo_Launcher](https://user-images.githubusercontent.com/62773866/207171150-bb545801-6f5b-4bcb-8f9c-ffe536ece0a6.png)

**Comment by IzzySoft** [comment]
> we'll possibly merge as it is and see from there

OK, then I'll include both, the Perl script and the generated `.txt`, and let you decide when looking at it.

> when there's again a unique number to get.

Two unique numbers upcoming now, making it 3 in a row: 1000 – and the 1001<sup>st</sup> night right after. Then, a little later, we go for some (more) binaries: 1010 and 1011. The next ones (1100, 1101, 1110, 1111) will take a while to reach…

Now, all the best for your health! And should I one day be in my birth-town again, maybe we have a drink together…

Oh, screenshots crossing – will be added ASAP :smiley:

**Comment by machiav3lli** [comment]
@IzzySoft gerne, you can write me over [TG](https://t.me/antonios_hazim), [Matrix](https://matrix.to/#/@machiav3lli:matrix.org), Email(antonios.hazim[ät]tutanota punkt com) or Fax (just joking). If you prefer other channels (e.g. fax) just tell me.

**Comment by IzzySoft** [comment]
As I don't use TG or Matrix, I'll have to remember the email address then I guess :wink:

PR opened.

**Comment by IzzySoft** [comment]
Thanks for merging! Metadata updated here, will now be pulled along with future releases. Last step: Adding [a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to the readme, maybe? :smiley:

**Comment by IzzySoft** [comment]
Oh, and I guess whoever adds the badge can have that PR close this issue then, right? :smile:

**Comment by IzzySoft** [comment]
Uh? Closed without a badge? :cry:

**Comment by saulhdev** [comment]
Sorry I did it from my phone by mistake. I will add the badge later tonight

**Comment by IzzySoft** [comment]
Thanks!

**Comment by machiav3lli** [comment]
> As I don't use TG or Matrix, I'll have to remember the email address then I guess wink
> 
> PR opened.

What about Signal?

**Comment by IzzySoft** [comment]
Nope, neither. Threema, XMPP, Mail. And Mastodon of course :wink:

**Comment by machiav3lli** [comment]
@IzzySoft ok, then let's stay on email for now.
