### ISSUE TITLE
[Bug] Random crashes

### ISSUE THREAD

**Issue by Terkyz** [NeoApplications/Neo-Feed#19]
**Describe the bug**
Without really any defined pattern, Neo-Feed crashes unexpectedly and stops working. Once that happens, I can go into the app whenever I want but the "Neo Feed" tab that appears when I slide my finger to the right in the main menu just doesn't open, it's like it's not there. Restarting my device does not fix the problem either.

**To Reproduce**
Sometimes it happens when opening the Neo-Feed tab and browsing the feeds, sometimes when trying to add a new feed, sometimes it randomly does not work without reason.

**Expected behavior**
No crashes

**Screenshots**
When It fail I will share a video of the bug, but since it's basically random it's a bit difficult.

**Neo Feed Version(please complete the following information):**
 - Version 1.4.4

**Smartphone (please complete the following information):**
 - Device: Samsung A10
 - OS: Android 11
 - Version IDK
 - Launcher Neo-Launcher 0.9.3

**Additional context**
Once the app stops crashing it works perfectly for a long time, but at some point it crashes without reason although it is unlikely, also, since the problem started I turned off the battery optimizations for Neo-Feed and it didn't really change anything, and I want to clarify that the app it is actually running, it just doesn't open the feed window, since an icon of the app appears in my notification panel, although I don't remember what it says.

**Comment by lxwulf** [comment]
I can confirm this. I have notifications about "This App "Neo Feed" has stopped working.". Also, completely random.

**Comment by citizenserious** [comment]
Might be related to https://github.com/NeoApplications/Neo-Feed/issues/13

**Comment by saulhdev** [comment]
Fixed on v1.4.5
