### ISSUE TITLE
[feature] toggle feed entries

### ISSUE THREAD

**Issue by Psk-Ita** [NeoApplications/Neo-Feed#20]
**Describe the bug**
Could be nice to have an option to temporarly disable one or more feed source

Thanks

**Comment by saulhdev** [comment]
comming soon
![Screenshot_20230220-213903_Neo Feed](https://user-images.githubusercontent.com/6044050/220241831-68011834-4fa0-4988-a4dc-317cc463835b.jpg)

**Comment by Psk-Ita** [comment]
nice! thank you!
