### ISSUE TITLE
After update, it crush every-time, not functional anmore.

### ISSUE THREAD

**Issue by Getron** [NeoApplications/Neo-Feed#22]
**Describe the bug**
After todays update, it doesn't work anymore on Redmi Note 9 Pro with Android 12 and MiUI 14, with Neo launcher, it crash with a bug, and downs even show the feeds on the left side, can't scroll left anymore.

**To Reproduce**
1. Go to Data sources ( to Add or remove sources)
2. Click on one of the added source - it will crash, immediately.
3. RSS's was previously added, with previous version of Neo Feed, before this update today. I have try to remove previously added RSS's, and added it with the new version, but, the same bug.
4. See error:

java.lang.RuntimeException: Invalid TypeToken; must specify type parameters
	at hfcore.r44.<init>(Unknown Source:39)
	at hfcore.ba0.<init>(Unknown Source:0)
	at hfcore.kv0.b(SourceFile:142)
	at hfcore.vr3.n(SourceFile:20)
	at hfcore.vr3.w0(Unknown Source:12)
	at hfcore.sg2.G(SourceFile:5)
	at hfcore.s8.K0(SourceFile:72)
	at hfcore.gk2.n(SourceFile:68)
	at hfcore.yj.l(Unknown Source:8)
	at hfcore.ej0.run(Unknown Source:100)
	at hfcore.uy1.run(Unknown Source:11)
	at hfcore.ft3.run(Unknown Source:2)
	at hfcore.o80$a.run(SourceFile:82)
	Suppressed: hfcore.vh0: [CoroutineName(NeoFeedSync), ol3{Cancelling}@e0cc194, Dispatchers.IO]

**Expected behavior**
Should be able to edit or add sources, and should be able to view feed on Neo Launcher on the left desktop - but, it doesn't work anymore, not able to scroll left the Neo Launcher desktop anymore.

**Screenshots**

**Neo Feed Version(please complete the following information):**
 - Version 1.4.5 ( Build 44 )

**Smartphone (please complete the following information):**
 - Device: Redmi Note 9 Pro and MI 11 Lite 5G
 - OS: Android 12 and Android 13
 - Version of both phones is MIUI 14

**Additional context**
In the older version of Neo Feed, I was not able to open RSS Feeds, sometimes, but, if i switch Open in Browser, or not, sometimes, it was able to open feeds in self browser, or Brave browser, but, this is an bug too, please to check.

**Comment by gpuccio87** [comment]
Similar problem here. Oneplus 9 Pro, Neo Launcher:

It crashed every time I opened Neo Feed or scrolled left from my Home Page. I solved this problem by clearing the app's memory. I lost my RSS sources (not such a big problem), but there is another problem: the app crashes every time I try to import an OPML file (from the clipboard app).

**Comment by saulhdev** [comment]
there are a lot of changes on the database and that might be causing the crashes.
It might require to clear data and add the rss again.

**Comment by scimitar4444** [comment]
I can confirm this. On my device, Alioth Poco F3 under /e/ current version Android 12.1 the same behaviour. Deleting the data and creating a new one also leads to a crash of the app as soon as the first feed is entered.

**Comment by saulhdev** [comment]
It has been fixed temporary. You can download the last build from the telegram channel. A new release will be available in the next days at github.

**Comment by saulhdev** [comment]
Fixed on v1.5.0
