### ISSUE TITLE
FR: Add option to remove duplicate links in feed

### ISSUE THREAD

**Issue by machiav3lli** [NeoApplications/Neo-Feed#25]
### Discussed in https://github.com/NeoApplications/Neo-Feed/discussions/24

<div type='discussions-op-text'>

<sup>Originally posted by **spart0n654** July 22, 2023</sup>
Basically I use this to replace my Google news feed and I have several local cities that I am following and I put them in the app but unfortunately Google news puts many of the news articles in multiple cities I follow so when I put all of them in neo feed I get a lot of duplicate links but are listed under different feed sources. Is there any way to have it remove duplicate links when it refreshes? </div>

**Comment by saulhdev** [comment]
can you share the feed urls so I can find a way to identify if the content is the same?

**Comment by machiav3lli** [comment]
Added in 1.7.0
