### ISSUE TITLE
Composables in ComposeOverlayView do not recompose on state changes

### ISSUE THREAD

**Issue by RyanKoech** [NeoApplications/Neo-Feed#29]
**Describe the bug**
Composables in ComposeOverlayView do not recompose on state changes

**To Reproduce**
1. Install latest Neo-Feed on main branch
2. Go to Install Neo Launcher. Head at [this commit](https://github.com/NeoApplications/Neo-Launcher/commit/54cc87691326b5fcc3b42a2c5639b21b3e2c6b1c)
3. Go to launcher settings, Search & Feed, Set Neo Feed as Launcher Feed
4. Go back to home screen
5. Scroll right to open feed from left
6. Click top right nut icon
7. Observe drawer not shown

**Expected behavior**
Drawer should be shown

**Screenshots**

**Neo Feed Version(please complete the following information):**
 - Version 1.6.3

**Smartphone (please complete the following information):**
 - Device: 10.1  WXGA (Tablet) Emulator
 - OS: Android API 34
 
 
**Additional context**

**Comment by machiav3lli** [comment]
ComposeOverlayView was a first (till now not fully successful) try to migrate fully to Compose.

In the following versions we'll give it another try. Till then, the community groups are the place for reporting on tests & similar stuff, as it's less effort for us to communicate there.
