### ISSUE TITLE
My want credit so Turkish translate

### ISSUE THREAD

**Issue by Sxinar** [NeoApplications/Neo-Feed#31]
Hello, I decided to use Neo feed and I saw that I increased the Turkish translation from 32% to 84%. I will finish it completely in my spare time. I am new on Github, where will I enter my contribution on the project page? Is credit given? Sorry, I am new. Success?

**Comment by machiav3lli** [comment]
Weblate handles this automatically when you use the same email for Weblate and Git(Hub)

**Comment by machiav3lli** [comment]
Like this commit: https://github.com/NeoApplications/Neo-Feed/commit/50a9acb2c1657c0584b427009c1b48367a39d4c7
