### ISSUE TITLE
Sometimes unable to delete last data source due to "+" button location

### ISSUE THREAD

**Issue by fishears** [NeoApplications/Neo-Feed#32]
**Describe the bug**
Occasionally, depending on the list of data sources, it can be either difficult or completely impossible to touch the "X" to delete the lowest data source on the screen. This is due to the position on the "+" button. Maybe moving the delete buttons to the left of each data source would be a good idea.

**To Reproduce**
three-dot menu > settings > data sources

**Expected behavior**
The delete buttons for all data sources should be visible/accessible at all times

**Screenshots**
![image](https://github.com/user-attachments/assets/838d952b-1273-4bf5-8459-c7746997d460)

**Neo Feed Version(please complete the following information):**
 - 1.6.2 (Build 55)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A22 5G
 - OS: Android
 - Version 13

**Comment by machiav3lli** [comment]
Fixed in 1.7.0
