### ISSUE TITLE
FR: OPML Import

### ISSUE THREAD

**Issue by pr0927** [NeoApplications/Neo-Feed#9]
Hello, would LOVE to see a feature to import an OMPL list of RSS feeds. I have a silly amount of subscriptions and categorized into different topic areas. Loving what I'm seeing here so far, but of course it's a bit too rough individually adding each RSS feed. Being able to import the entire listing would be a godsend. Hoping to see this here!

**Comment by gpuccio87** [comment]
Would love it too!

**Comment by machiav3lli** [comment]
Actually it should be already done (https://github.com/NeoApplications/Neo-Feed/commit/e42c245a965258fe82a53ef7d80559ccc2694f13)

**Comment by gpuccio87** [comment]
Didn't saw it. Thank you, I will wait for the next release.
